// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"order/internal/conf"
	"order/internal/repo"
	"order/internal/server"
	"order/internal/service"
	"order/internal/usecase"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, auth *conf.Auth, confService *conf.Service, logger log.Logger) (*kratos.App, func(), error) {
	db := repo.NewDB(confData)
	client := repo.NewRedis(confData)
	dataData, cleanup, err := repo.NewData(confData, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	orderRepo := repo.NewOrderRepo(dataData, logger)
	discovery := repo.NewDiscovery(registry)
	userClient := repo.NewUserServiceClient(auth, confService, discovery)
	cartClient := repo.NewCartServiceClient(auth, confService, discovery)
	goodsClient := repo.NewGoodsServiceClient(auth, confService, discovery)
	orderUsecase := usecase.NewOrderUsecase(orderRepo, userClient, cartClient, goodsClient, logger)
	orderService := service.NewOrderService(orderUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, orderService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
